name: bot-delete-old-runs

on:
#   schedule:
#     - cron: '0 0,6,12,18 * * *'
  workflow_dispatch: null

jobs:
  delete-old-runs:
    name: delete-old-runs
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          create-args: "python==${{ vars.PYVER }}"
          init-shell: bash
          cache-environment: false
          environment-name: cf-scripts
          post-cleanup: 'all'
          condarc: |
            channels:
              - conda-forge

      - name: delete runs
        shell: bash -l {0}
        run: |
          python autotick-bot/delete_old_runs.py
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOTICK_BOT_TOKEN }}
