name: keepalive
on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  cronjob-based-github-action:
    name: Cronjob based github action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: gautamkrishnar/keepalive-workflow@7fa96d25d8e4c2811d5405d6328111f1ef548246 # v2
        with:
          commit_message: "Ah ah ah, stayin' alive"
          committer_username: conda-forge-bot
          committer_email: "conda-forge-bot@users.noreply.github.com"
          time_elapsed: 50 # days
          use_api: false
