name: test-model

on:
  workflow_dispatch:
  schedule:
    - cron: "10 8 * * *"  # every hour

env:
  PY_COLORS: "1"

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-lock.yml
          environment-name: cf-scripts
          condarc-file: autotick-bot/condarc

      - name: configure conda, install code, and clone cf-graph
        run: |
          pip install --no-deps --no-build-isolation -e .
          git clone --depth=1 https://github.com/regro/cf-graph-countyfair.git cf-graph

      - name: conda info and env
        run: |
          echo "=================================================================="
          echo "=================================================================="
          conda info

          echo ""
          echo "=================================================================="
          echo "=================================================================="
          conda list

      - name: run pytest (model)
        run: |
          cd cf-graph
          pytest \
            -v \
            --durations 10 \
            ../tests/model
